version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: npm install
       - run: CI=true npm run build
   test:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: npm install
       - run: npm run test
   gratitude:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: echo "Thank God!"
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - gratitude
      - test:
          requires:
            - gratitude